### ISSUE TITLE
Suggestion: rename category "SuperComputing" to "Performance"

### ISSUE THREAD

**Issue by ffevotte** [djsegal/julia_packages#177]
The rationale would be that everything related to SuperComputing also relates to Performance. However, there are tools for performance (like benchmarking or compilation tools for example) that are useful in more general contexts than SuperComputing.

**Comment by djsegal** [comment]
At the moment, I don't think we are going to rename any of the category names that came from the svaksha's [decibans](https://svaksha.github.io/Julia.jl/)
