### ISSUE TITLE
Potential missing package

### ISSUE THREAD

**Issue by darrencl** [djsegal/julia_packages#186]
Hi, I have registered a package for feature selection, named `FeatureSelector.jl`. It is already registered in the general registry [here](https://github.com/JuliaRegistries/General/tree/master/F/FeatureSelectors), but I could not find it in Julia package website. Am I missing anything here?

Thanks

**Comment by zachmatson** [comment]
My package `ArgMacros.jl` doesn't show the most up-to-date info either, and the latest version was released in September or so.

**Comment by djsegal** [comment]
See:

- https://juliapackages.com/packages/featureselectors
- https://juliapackages.com/packages/argmacros

// caused by same issue discussed in #190
