### ISSUE TITLE
"Update last" tab not up to date?

### ISSUE THREAD

**Issue by mforets** [djsegal/julia_packages#190]
Eg. https://juliapackages.com/p/modelingtoolkit says Updated Last 10 Months Ago but I think it should say something like "about 14 hours ago", compare with https://juliaobserver.com/packages/ModelingToolkit (scroll down to "Last Touched"). .

**Comment by djsegal** [comment]
This is caused by the website being manually updated. JuliaObserver solves this by updating with workers for example

That being said, it is now up to date (through yesterday)

**Comment by mforets** [comment]
OK, thanks for the feedback!
