### ISSUE TITLE
CFITSIO.jl error

### ISSUE THREAD

**Issue by ghost** [djsegal/julia_packages#208]
Facing this error from CFITSIO.jl
``
> ERROR: CFITSIO has encountered an error. Error code 412: datatype conversion overflow
> Detailed error message follows: 
> Numerical overflow during type conversion while writing FITS data.
> Stacktrace:
>  [1] fits_assert_ok
>    @ ~/.julia/packages/CFITSIO/nSUZm/src/CFITSIO.jl:225 [inlined]
>  [2] fits_assert_ok
>    @ ~/.julia/packages/CFITSIO/nSUZm/src/CFITSIO.jl:219 [inlined]
>  [3] fits_write_col(f::CFITSIO.FITSFile, colnum::Int64, firstrow::Int64, firstelem::Int64, data::Vector{Int16})
   @ CFITSIO ~/.julia/packages/CFITSIO/nSUZm/src/CFITSIO.jl:2604
 [4] sxt_l2evtlist_merge(l2evtfilelist::String, merged_evtfile::String)
   @ SXTMerger ~/.julia/packages/SXTMerger/UGgRo/src/sxt_l2evtlist_merge.jl:96
 [5] top-level scope
``

**Comment by djsegal** [comment]
?

I don't think this is related to this project. 

@ghost, maybe check out: https://github.com/JuliaAstro/CFITSIO.jl
