### ISSUE TITLE
Everything is "updated last" at least a year ago

### ISSUE THREAD

**Issue by frankier** [djsegal/julia_packages#226]
For me, even when browsing very recently updated packages, such as https://juliapackages.com/p/jump , the "updated last" will say "a year ago". This makes the ecosystem seem less active than it actually is. How about "less than n months" where n \in 1..12?

**Comment by djsegal** [comment]
Bump. Will update site shortly

**Comment by KronosTheLate** [comment]
Despite [makie.jl](https://github.com/MakieOrg/Makie.jl) having over 2.2k stargazers, [the JuliaPackages page for Makie](https://juliapackages.com/p/makie) shows 1978 stargazers. Why is JuliaPackages.com not updated automatically? For reference, @hyrodium was able to provide updated stars to [JuliaPackageComparisons.github.io](https://juliapackagecomparisons.github.io/pages/plotting/index.html#makiejl).

**Comment by djsegal** [comment]
I got a 404 from https://juliapackagecomparisons.github.io/pages/plotting/index.html#makiejl?

Sorry, just updated it recently. Will try to update more frequently moving forward

**Comment by hyrodium** [comment]
The directory structure was updated. Here's a new link:
https://juliapackagecomparisons.github.io/comparisons/graphics/plotting/
