### ISSUE TITLE
WGPU related packages not listed on juliapackages

### ISSUE THREAD

**Issue by arhik** [djsegal/julia_packages#230]
The following packages are not listed on juliapackages site. These packages are already on registry. Not sure why ?

- WGPUCore (https://github.com/dvijaha/WGPUCore.jl)
- WGPUNative (https://github.com/dvijaha/WGPUNative.jl)
- WGSLTypes (https://github.com/dvijaha/WGSLTypes.jl)
- WGPUgfx (https://github.com/dvijaha/WGPUgfx.jl)
- WGPUCompute (https://github.com/dvijaha/WGPUCompute.jl)

**Comment by arhik** [comment]
search result is empty on juliapackage for these packages

**Comment by djsegal** [comment]
I don't see WGSLTypes, but the rest are visible at:

https://juliapackages.com/packages?search=WGPU
