### ISSUE TITLE
Add Sort By Label next to Sort Options

### ISSUE THREAD

**Issue by g-adel** [djsegal/julia_packages#249]
It took me an embarrassingly long amount of time to find the sorting options at the top. I think having a label stating that these are sorting options would greatly help.

**Comment by djsegal** [comment]
Tolle Idee, resolved in: https://github.com/djsegal/julia_packages/commit/932d5695e0d5b41ad61af46eeb27b67a3fe060c1

Kind of an idiot when it comes to these UX things sometimes
