### ISSUE TITLE
juliapackages.com - TLS certificate expired 

### ISSUE THREAD

**Issue by xwjqv** [djsegal/julia_packages#250]
The TLS certificate of the juliapackages.com website is expired.
Most browsers warn of security issues because of it.

**Comment by younes-io** [comment]
@djsegal could you please take a look at this?
Thank you

**Comment by technocrat** [comment]
2024-05-03 00:27 PDT— still down

**Comment by djsegal** [comment]
Apologies. Should be back up now. Will update DB shortly as well

**Comment by younes-io** [comment]
awesome, thank you
@xwjqv  I think this can be closed =)

![image](https://github.com/djsegal/julia_packages/assets/3153107/004d8dfc-5917-4f0a-98bf-3eecc5101cd1)
