### ISSUE TITLE
Package (Allocations.jl) not updated

### ISSUE THREAD

**Issue by mlhetland** [djsegal/julia_packages#253]
I’m sorry if I’m just being dense, but it seems the following page is not updated…?

https://juliapackages.com/p/allocations

It says the last update to Allocations.jl was a year ago, but the last version was actually released in May (and there have been updates on GitHub after that), cf. https://github.com/mlhetland/Allocations.jl (and https://github.com/JuliaRegistries/General/tree/master/A/Allocations).

**Comment by djsegal** [comment]
Sorry about that. Just updated it. Danke ツ
